[server]
host = "127.0.0.1"
port = 8080

[database]
max_connections = 10

[application]
name = "Hotel Plus"
environment = "development"

[security]
session_duration = 3600

[imagekit]
url = "https://ik.imagekit.io/your_id/"
