[package]
name = "infrastructure"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
diesel = { version = "2", features = ["postgres", "chrono", "uuid", "numeric"] }
diesel-async = { version = "0.5", features = ["postgres", "deadpool"] }
deadpool = "0.10"
uuid = "1.0"
chrono = "0.4"
core = { path = "../core" }
